### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by MFernflower** [QuantumCorona/AutodockVina_3CL-pro#1]
Would you be able to dock all of my designed compounds to the enzyme? They are all prefixed with ANT-OPE in https://covid.postera.ai/covid/submissions (I think 20 compounds total maybe as some submissions have like 3 or so)

I thank you for your work! @jarvist

**Comment by jarvist** [comment]
Yep, can do! 
The rate limiting step is copy+pasting the SMILES by hand into a e.g. "ANT-OPE-ab3.smi" file. Do you have the raw data?

**Comment by MFernflower** [comment]
For now I am interested in just *ANT-OPE-a51 and ant-ope-6a1 *

**Comment by MFernflower** [comment]
*ANT-OPE-a51-1*

C1(=CC=CC=C1)C1=CC(=CN1S(=O)(=O)C=1C=NC=CC1)CN(C)C


*ANT-OPE-7c1-1*

CCC(=O)NCC[C@@H]1CCC2=C1C=CC=C2


*ANT-OPE-6a1-2*

C1=CC=C(C2=CC=CC=C12)[C@H]1[C@@H](C1)CNC(CC)=O


*ANT-OPE-6a1-1*

C1=CC=C(C=C1)[C@H]1[C@@H](C1)CNC(CC)=O

@jarvist 

Extracted smiles

**Comment by jarvist** [comment]
Perfect timing! Running an initial dock now.

**Comment by jarvist** [comment]
a51: (Looks snug and happy!)
![ANT-OPE-a51_ligand_1_out](https://user-images.githubusercontent.com/82852/78460651-7f4d7a00-76ba-11ea-95a1-7152415b6427.png)
7c1:
![ANT-OPE-7c1_ligand_1_out](https://user-images.githubusercontent.com/82852/78460653-82486a80-76ba-11ea-9185-eff5d8f7847d.png)
6a1-2:
![ANT-OPE-6a1_ligand_2_out](https://user-images.githubusercontent.com/82852/78460654-83799780-76ba-11ea-973c-fa08d7d760f4.png)
6a1-1:
![ANT-OPE-6a1_ligand_1_out](https://user-images.githubusercontent.com/82852/78460655-84122e00-76ba-11ea-87ea-2c2e7225df66.png)

**Comment by jarvist** [comment]
https://github.com/QuantumCorona/AutodockVina_3CL-pro/tree/master/0013-ANT-OPE

**Comment by MFernflower** [comment]
Thank you!
